/**
 * @file chip_config.h
 * @brief ESP32-C6 Chip Configuration — Compatibility Shim
 *
 * All hardware constants are generated by the Toob Manifest Compiler from
 * hardware.json into generated_boot_config.h. This file provides backward-
 * compatible aliases for legacy names used by startup.c.
 *
 * NEW CODE SHOULD USE generated_boot_config.h macros directly.
 */

#ifndef CHIP_CONFIG_H
#define CHIP_CONFIG_H

#include "generated_boot_config.h"

/* ========================================================================
 * WDT Register Aliases (for startup.c wdt_sterilize_all)
 *
 * startup.c runs BEFORE the WDT driver and needs direct register addresses.
 * These are derived from the base addresses in generated_boot_config.h.
 * ======================================================================== */
#define REG_TIMG0_WDT_CONFIG0      (CHIP_REG_TIMG0_WDT_BASE + 0x48U)
#define REG_TIMG0_WDT_FEED         (CHIP_REG_TIMG0_WDT_BASE + 0x60U)
#define REG_TIMG0_WDT_WPROTECT     (CHIP_REG_TIMG0_WDT_BASE + 0x64U)

#define REG_TIMG1_WDT_CONFIG0      (CHIP_REG_TIMG1_WDT_BASE + 0x48U)
#define REG_TIMG1_WDT_WPROTECT     (CHIP_REG_TIMG1_WDT_BASE + 0x64U)

#define REG_LP_WDT_CONFIG0         (CHIP_REG_LP_WDT_BASE + 0x00U)
#define REG_LP_WDT_WPROTECT        (CHIP_REG_LP_WDT_BASE + 0x18U)
#define REG_LP_WDT_SWD_CONFIG      (CHIP_REG_LP_WDT_BASE + 0x1CU)
#define REG_LP_WDT_SWD_WPROTECT    (CHIP_REG_LP_WDT_BASE + 0x20U)

/* ========================================================================
 * Reset Reason Aliases
 * ======================================================================== */
#define REG_RESET_CAUSE            (CHIP_REG_PMU_BASE + CHIP_RST_CAUSE_OFFSET)
#define REG_RESET_CAUSE_MASK       CHIP_RST_CAUSE_MASK

/* ========================================================================
 * Confirm Storage Alias (typed pointer for confirm driver)
 * ======================================================================== */
#define ADDR_CONFIRM_RTC_RAM       ((volatile uint64_t *)(uintptr_t)CHIP_REG_RTC_RAM_BASE)

#endif /* CHIP_CONFIG_H */
